baseURL = "https://davidmurphy.netlify.com/"
languageCode = "en-us"
title = "David Murphy"
theme = "ghostwriter"
copyright = "David Murphy"
# googleAnalytics = "XXX"
# disqusShortname = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "David Murphy"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "David Murphy"
    description = "Up and Coming Developer"
    github = "https://github.com/DavidKroncke"
    linkedin = "https://www.linkedin.com/in/david-kroncke-935636178/"
    stackoverflow = "https://stackoverflow.com/users/10873422/david-kroncke"
    email = "david.ryan.kroncke@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4